// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/commerce": {
    params: {};
  };
  "/local-seo": {
    params: {};
  };
  "/news": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/recruit": {
    params: {};
  };
  "/site-map": {
    params: {};
  };
  "/store-info": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/commerce" | "/local-seo" | "/news" | "/privacy" | "/recruit" | "/site-map" | "/store-info" | "/terms" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./commerce/page.jsx": {
    id: "commerce/page";
    page: "/commerce";
  };
  "./local-seo/page.jsx": {
    id: "local-seo/page";
    page: "/local-seo";
  };
  "./news/page.jsx": {
    id: "news/page";
    page: "/news";
  };
  "./privacy/page.jsx": {
    id: "privacy/page";
    page: "/privacy";
  };
  "./recruit/page.jsx": {
    id: "recruit/page";
    page: "/recruit";
  };
  "./site-map/page.jsx": {
    id: "site-map/page";
    page: "/site-map";
  };
  "./store-info/page.jsx": {
    id: "store-info/page";
    page: "/store-info";
  };
  "./terms/page.jsx": {
    id: "terms/page";
    page: "/terms";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};